### ISSUE TITLE
安卓自动安装，下载完成后报错

### ISSUE THREAD

**Issue by developeng** [781238222/flutter-do#24]
E/MethodChannel#flutter_app_upgrade(19928): Failed to handle method call
E/MethodChannel#flutter_app_upgrade(19928): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
E/MethodChannel#flutter_app_upgrade(19928): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:605)
E/MethodChannel#flutter_app_upgrade(19928): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
E/MethodChannel#flutter_app_upgrade(19928): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
E/MethodChannel#flutter_app_upgrade(19928): 	at com.flutter.flutter_app_upgrade.FlutterAppUpgradePlugin.startInstall(FlutterAppUpgradePlugin.kt:180)
E/MethodChannel#flutter_app_upgrade(19928): 	at com.flutter.flutter_app_upgrade.FlutterAppUpgradePlugin.onMethodCall(FlutterAppUpgradePlugin.kt:67)
E/MethodChannel#flutter_app_upgrade(19928): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#flutter_app_upgrade(19928): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter_app_upgrade(19928): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#flutter_app_upgrade(19928): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_app_upgrade(19928): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter_app_upgrade(19928): 	at android.os.Looper.loop(Looper.java:189)
E/MethodChannel#flutter_app_upgrade(19928): 	at android.app.ActivityThread.main(ActivityThread.java:7201)
E/MethodChannel#flutter_app_upgrade(19928): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_app_upgrade(19928): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
E/MethodChannel#flutter_app_upgrade(19928): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:956)
E/flutter (19928): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference, null)
E/flutter (19928): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (19928): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (19928): <asynchronous suspension>
E/flutter (19928): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (19928): #3      FlutterUpgrade.installAppForAndroid (package:flutter_app_upgrade/src/flutter_upgrade.dart:32:27)
E/flutter (19928): #4      _SimpleAppUpgradeWidget._downloadApk.<anonymous closure> (package:flutter_app_upgrade/src/simple_app_upgrade.dart:348:26)
E/flutter (19928): #5      DioForNative.download.<anonymous closure>.<anonymous closure> (package:dio/src/entry/dio_for_native.dart:164:30)
E/flutter (19928): #6      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (19928): #7      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (19928): #8      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter (19928): #9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter (19928): #10     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter (19928): #11     Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter (19928): #12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
E/flutter (19928): #13     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (19928): #14     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (19928): #15     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (19928): #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter (19928): #17     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter (19928): #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)

**Comment by developeng** [comment]
android:authorities="app包名.fileprovider"
