### ISSUE TITLE
mContext.getExternalFilesDir("") must not be null

### ISSUE THREAD

**Issue by changcaichao** [781238222/flutter-do#45]
麻烦帮忙看下，在安卓5.0以下的设备中出现该问题

W/ContextImpl( 5120): Unable to create external files directory
E/MethodChannel#flutter_app_upgrade( 5120): Failed to handle method call
E/MethodChannel#flutter_app_upgrade( 5120): java.lang.IllegalStateException: mContext.getExternalFilesDir("") must not be null
E/MethodChannel#flutter_app_upgrade( 5120):     at com.flutter.flutter_app_upgrade.FlutterAppUpgradePlugin.onMethodCall(FlutterAppUpgradePlugin.kt:62)
E/MethodChannel#flutter_app_upgrade( 5120):     at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter_app_upgrade( 5120):     at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter_app_upgrade( 5120):     at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#flutter_app_upgrade( 5120):     at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_app_upgrade( 5120):     at android.os.MessageQueue.next(MessageQueue.java:132)
E/MethodChannel#flutter_app_upgrade( 5120):     at android.os.Looper.loop(Looper.java:124)
E/MethodChannel#flutter_app_upgrade( 5120):     at android.app.ActivityThread.main(ActivityThread.java:5136)
E/MethodChannel#flutter_app_upgrade( 5120):     at java.lang.reflect.Method.invokeNative(Native Method)
E/MethodChannel#flutter_app_upgrade( 5120):     at java.lang.reflect.Method.invoke(Method.java:525)
E/MethodChannel#flutter_app_upgrade( 5120):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
E/MethodChannel#flutter_app_upgrade( 5120):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/MethodChannel#flutter_app_upgrade( 5120):     at dalvik.system.NativeStart.main(Native Method)

**Comment by 781238222** [comment]
好的，我看下。

**Comment by niumenglin** [comment]
没有下文了？
