### ISSUE TITLE
为什么酷安的我总是跳转不过去, 提示手机没有安装, 其他的都可以

### ISSUE THREAD

**Issue by sobriver** [781238222/flutter-do#46]
W/System.err(18662): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.coolapk.market/com.coolapk.market.activity.AppViewActivity}; have you declared this activity in your AndroidManifest.xml?
W/System.err(18662): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2065)
W/System.err(18662): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
W/System.err(18662): 	at android.app.Activity.startActivityForResult(Activity.java:5320)
W/System.err(18662): 	at android.app.Activity.startActivityForResult(Activity.java:5278)
W/System.err(18662): 	at android.app.Activity.startActivity(Activity.java:5664)
W/System.err(18662): 	at android.app.Activity.startActivity(Activity.java:5617)
W/System.err(18662): 	at com.flutter.flutter_app_upgrade.FlutterAppUpgradePlugin.toMarket(FlutterAppUpgradePlugin.kt:129)
W/System.err(18662): 	at com.flutter.flutter_app_upgrade.FlutterAppUpgradePlugin.onMethodCall(FlutterAppUpgradePlugin.kt:75)
W/System.err(18662): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
W/System.err(18662): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err(18662): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
W/System.err(18662): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(18662): 	at android.os.MessageQueue.next(MessageQueue.java:335)
W/System.err(18662): 	at android.os.Looper.loop(Looper.java:183)
W/System.err(18662): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
W/System.err(18662): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(18662): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
W/System.err(18662): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by LiWenHui96** [comment]
酷安的Activity变了，目前为"com.coolapk.market.view.app.AppViewV8Activity"
